apiVersion: apps/v1
kind: Deployment
namespace: default
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: salimbouazizi/pfe_frontend:0.0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
namespace: default
metadata:
  name: angular-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081  # Port range 30000-32767
  selector:
    app: angular-app
