apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: salimbouazizi/pfe_backend_image:0.0.1
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysqlmysql.default.svc:3306/pfedb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "salim"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.MySQL8Dialect
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30007
