apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pvv
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/azureuser/mydb
    type: DirectoryOrCreate
