apiVersion: v1
kind: Pod
metadata:
  name: openvpn-test
  namespace: default
spec:
  containers:
    - name: openvpn
      image: dperson/openvpn-client
      args:
        - '-v'
        - '-r'
        - '192.168.1.100/32'
        - '-d'
        - '--'
        - '162.120.187.253'
      volumeMounts:
        - name: vpn-certs
          mountPath: /vpn
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: vpn-certs
      secret:
        secretName: vpn-credentials
