apiVersion: apps/v1
kind: Deployment
namespace: default
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: salimbouazizi/pfe_backend:0.0.2
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://192.168.1.100:3306/pfedb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "salim"
---
apiVersion: v1
kind: Service
namespace: default
metadata:
  name: springboot-service
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30007
  selector:
    app: springboot-app
