apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: salimbouazizi/pfe_backend:0.0.2
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://192.168.1.100:3306/pfedb?useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "salim"
      - name: openvpn-client
        image: dperson/openvpn-client:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: openvpn-config
          mountPath: "/vpn"
        command: ["/sbin/openvpn", "--config", "/vpn/client.ovpn"]
      volumes:
      - name: openvpn-config
        secret:
          secretName: openvpn-client
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30007
  selector:
    app: springboot-app



