apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: salimbouazizi/pfe_backend:0.0.2
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://197.1.112.42:3306/pfedb"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password

      - name: openvpn
        image: dperson/openvpn-client
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: vpn-credentials
          mountPath: "/vpn"
        args:
        - "-v"
        - "-r 192.168.1.100/32"
        - "-d"
        - "-f /vpn/ca.crt,/vpn/client.crt,/vpn/client.key"
        - "162.120.187.253"  # <-- Replace with your actual router IP

      volumes:
      - name: vpn-credentials
        secret:
          secretName: vpn-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30007
  selector:
    app: springboot-app
